// Import files

export default [
    {
        'id': 1,
        'name': '',
        'image': '',
        'github': '',
        'deploy': '',
    },
    {
        'id': 2,
        'name': '',
        'image': '',
        'github': '',
        'deploy': '',
    },
    {
        'id': 3,
        'name': '',
        'image': '',
        'github': '',
        'deploy': '',
    },
    {
        'id': 4,
        'name': '',
        'image': '',
        'github': '',
        'deploy': '',
    },
    {
        'id': 5,
        'name': '',
        'image': '',
        'github': '',
        'deploy': '',
    },
    {
        'id': 6,
        'name': '',
        'image': '',
        'github': '',
        'deploy': '',
    },
    {
        'id': 7,
        'name': '',
        'image': '',
        'github': '',
        'deploy': '',
    },
    {
        'id': 8,
        'name': '',
        'image': '',
        'github': '',
        'deploy': '',
    },
    {
        'id': 9,
        'name': '',
        'image': '',
        'github': '',
        'deploy': '',
    },
    {
        'id': 10,
        'name': '',
        'image': '',
        'github': '',
        'deploy': '',
    },
    {
        'id': 11,
        'name': '',
        'image': '',
        'github': '',
        'deploy': '',
    },
    {
        'id': 12,
        'name': '',
        'image': '',
        'github': '',
        'deploy': '',
    },
    {
        'id': 13,
        'name': '',
        'image': '',
        'github': '',
        'deploy': '',
    },
    {
        'id': 14,
        'name': '',
        'image': '',
        'github': '',
        'deploy': '',
    },
    {
        'id': 15,
        'name': '',
        'image': '',
        'github': '',
        'deploy': '',
    },
    {
        'id': 16,
        'name': '',
        'image': '',
        'github': '',
        'deploy': '',
    },
]